$vars:
  APP: &APP MVLAB
  NET: &NET cgan
  DATA_DIR: &DATA_DIR !join [apps, *APP, data]
  MODEL_DIR: &MODEL_DIR !join [apps, *APP, models]
  MODULE_DIR: &MODULE_DIR !join [apps, *APP, modules]
  CONFIG_DIR: &CONFIG_DIR !join [apps, *APP, configs, *NET]

data: !include [!join [*CONFIG_DIR, dataset]]
model:
  target: !join [*MODEL_DIR, model, *APP]
  params: 
    !merge [
      !include [!join [*CONFIG_DIR, args]],
      !include [!join [*CONFIG_DIR, pipline], pipconfig],
      !include [!join [*CONFIG_DIR, model], netconfig]
    ]